name: Run tests
on: push
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: docker://coqueirotree/docker-pyspark:0.0.1
      env:
        READ_PATH: test/data/part0.json
        WRITE_PATH: /output
        USER_KEY: user_key
        TIMESTAMP_KEY: timestamp_key
        MAX_SESSION_SECONDS: 3600
        GROUP_KEY: group_field1
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run tests
        run: |
          cd session-calc
          python3 -m unittest
